### PR TITLE
Redirects from delegate to address page if the id doesn't belong to a delegate

### LINKED ISSUE #143: Delegate page should not be accessible for normal accs
Current behavior:
Delegate page is accessible via direct link for non-delegate accounts and display broken page.

Expected behavior:
Delegate page should not be accessible for non-delegate accounts.

Steps to reproduce:
Enter delegate page of non-delegate acc, for example: `/delegate/2226471703256329822L`.

### PR DESCRIPTION
**Pull request by alihaghighatkhah**
Closes #143

### CODE REVIEW

File: src/components/delegate/delegate.component.js [hunk 1]
```diff
@@ -13,8 +13,12 @@ const DelegateConstructor = function ($rootScope, $stateParams, $location, $http
         }).then(resp => {
             if (resp.data.success) {
                 vm.address = resp.data;
+
+                if (!vm.address.delegate) {
+                    $state.go('address', { address: $stateParams.delegateId });
+                }
             } else {
-                throw 'Account was not found!';
+                $state.go('home');
```
Comment (slaweet) [inline src/components/delegate/delegate.component.js]: I would much rather get a 404 page in this case. Though it's not the concern of this issue/PR  but something to consider in future.

Comment (alihaghighatkhah) [inline src/components/delegate/delegate.component.js]: The reason I didn't redirect to 404 is that there are some problems with 404 component I prefer to solve them in a dedicated ticket.
