### PR TITLE
 Configure cookie expiry date - Closes #841

### LINKED ISSUE #841: Configure cookie expiry date
### Expected behavior
Cookies related to the cookie banner should have a two-year expiry date.

### Actual behavior
Currently, the cookie banner saves a cookie with a very short validity.
This brings the banner back in a short time period.

### Steps to reproduce
Open browser debug mode and accept the cookie policy. Cookie with invalid date will be shown.

### PR DESCRIPTION
**Pull request by youxiberlin**
### What was the problem?
Cookie expire date for the cookie banner was not working.

### How did I fix it?
- set expireDate to 2 years ahead on cookie-banner.directive.js

### How to test it?
- you can test it on console by removing the cookie and recreate the cookie

### Review checklist

* The PR solves #841 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the
	[commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: src/components/cookies-banner/cookies-banner.directive.js [hunk 1]
```diff
@@ -20,9 +20,13 @@ const directiveCtrl = ($scope, $cookies) => {
...
 	const cookieKey = 'cookiesBannerConfirmed';
 
+	// setting expireDate to 2 years ahead
+	const expireDate = new Date();
+	expireDate.setDate(expireDate.getDate() + 730);
+
 	$scope.clicked = () => {
 		$scope.visible = false;
-		$cookies.put(cookieKey, 'true');
+		$cookies.put(cookieKey, 'true', { 'expires': expireDate });
```
Comment (MichalTuleja) [inline src/components/cookies-banner/cookies-banner.directive.js]: Jenkins test fails on ESlint step. Once this line aligns to the ESlint rules, the tests should pass.

File: src/components/cookies-banner/cookies-banner.directive.js [hunk 2]
```diff
@@ -20,9 +20,13 @@ const directiveCtrl = ($scope, $cookies) => {
 	$scope.visible = true;
 	const cookieKey = 'cookiesBannerConfirmed';
 
+	// setting expireDate to 2 years ahead
+	const expireDate = new Date();
+	expireDate.setDate(expireDate.getDate() + 730);
```
Comment (MichalTuleja) [inline src/components/cookies-banner/cookies-banner.directive.js]: The `730` value should be written as `const` with a proper name.
