### PR TITLE
Invalid reverse dns fix - Closes #540

### LINKED ISSUE #540: Invalid reverse DNS query crashes the process
### Expected behavior
Invalid DNS query returns an IP in the `.unknown` domain.

### Actual behavior
Invalid DNS query crashes the process.

### Steps to reproduce
Hard to reproduce on production, but easy to simulate having access to the source code.
Change the line `lib/api/statistics.js:191` in the function  `Locator.getHostName` with the following pattern:
`dns.reverse(ip,` -> `dns.reverse('',`

### PR DESCRIPTION
**Pull request by MichalTuleja**
### What was the problem?
The built-in dns module raised an unhandled exception in case of invalid IP address.

### How did I fix it?
The failing code is wrapped around a try-catch block. Due to non-critical importance of this issue, we handle all reverse DNS problems same way - by returning a hostname in the following format: `nnn.nnn.nnn.nnn.unknown'.

### How to test it?
There is no clear way to reproduce the bug. The problem should not exist anymore on the alpha- and betanet.

### Review checklist
- The PR solves #540
- All new code is covered with unit tests
- All new features are covered with e2e tests
- All new code follows best practices

### CODE REVIEW

File: lib/api/statistics.js [hunk 1]
```diff
@@ -186,18 +186,23 @@ module.exports = function (app) {
...
+					} else {
+						hostname = hostnames[0];
+					}
 
-				return cb(err, hostname);
-			});
+					return cb(err, hostname);
+				});
+			} catch (err) {
+				cb(err, unknownHostname);
```
Comment (lsilvs) [inline lib/api/statistics.js]: Should it not be `cb(null, unknownHostname);` ?

Comment (lsilvs) [reply lib/api/statistics.js]: My bad. That's correct ;)
