### PR TITLE
Bug - empty transaction list - Closes #712

### LINKED ISSUE #712: Account: Empty transaction list
### Expected behavior
The transaction list should show last 50 transactions by default.

### Actual behavior
Some addresses show empty transaction list.
That might be caused by the function `normalizeTransactionParams` in the `transctions.js`.
The request that is sent contains lowercase `l` in the address.
`http://ams1-explorer-002.lisk.io:8000/api/transactions?orderBy=timestamp:desc&offset=0&limit=51&and:recipientId=91540l&or:senderId=91540l`

### Steps to reproduce
Search for  `91540L`.

### PR DESCRIPTION
**Pull request by MichalTuleja**
### What was the problem?
Some inputs are not properly parsed by the frontend client. It results with an empty transaction table on the account page. 

### How did I fix it?
The address input is always parsed against common issues: lowercase `L` and white characters.
This ensures that the core backend always receives an address in the following format: `12345L`.

### How to test it?
Visit the `91540L` page, transactions should be visible.

### Review checklist
- The PR solves #712
- All new code is covered with unit tests
- All new features are covered with e2e tests
- All new code follows best practices

### CODE REVIEW

**Comment by MichalTuleja** [comment]
@lsilvs It works as well.

Examples:
`http://localhost:6040/api/getAccount?address=163 137 396 616 706 346 66l`
`http://localhost:6040/api/getTransactionsByAddress?address=163 137 396 616 706 346 66l&limit=51&offset=0`

Note that this solution changes the backend only.

**Comment by lsilvs** [comment]
Try `http://localhost:6040/api/search?id=18234943547133247+982L`

**Comment by MichalTuleja** [comment]
@lsilvs I've fixed it for any characters except 0-9 and `l` `L`.
The search query is too long anyway.
Works fine using the transaction request.

**Comment by lsilvs** [comment]
I don't think we should change the input provided by the user apart from making it case-insensitive.

**Comment by MichalTuleja** [comment]
Also that the frontend should parse the data before they're sent to the Explorer backend.
I'll keep the case-insensitive rule only then.

File: test/api/accounts.js [hunk 1]
```diff
@@ -98,6 +99,14 @@ describe('Accounts API', () => {
 			});
 		});
 
+		it('using known lowercase address should be ok', (done) => {
```
Comment (lsilvs) [inline test/api/accounts.js]: This test doesn't test your implementation. You should test `getTransactionsByAddress` rather than `getAccount`
