### PR TITLE
Transaction view: Added/deleted votes are visible - Closes #535

### LINKED ISSUE #535: Transaction page: votes added/deleted not showing
### Expected behavior
When accessing `/tx/:transactionId` for a transaction type *VOTE*, you should see the votes added/deleted

### Actual behavior
Nothing is shown

### Steps to reproduce
Access /tx/:transactionId where `:transactionId` is an *VOTE* transaction

### PR DESCRIPTION
**Pull request by MichalTuleja**
### What was the problem?
Due to a change in the API the votes list in the transaction view was not present at all.

### How did I fix it?
The logic for votes is completely rewritten, making the code a little bit simpler and taking advantage of the new API.

### How to test it?
Visit a transaction page on a voting transaction.

### Review checklist
- The PR solves #535
- All new features are covered with e2e tests
- All new code follows best practices

### CODE REVIEW

File: lib/api/transactions.js [hunk 1]
```diff
@@ -306,48 +307,37 @@ module.exports = function (app) {
...
-								added.push({ publicKey: vote });
-							});
-
-							return async.forEach(added, (add, callback) => {
-								t.getDelegate(add, callback);
-							}, () => {
-								transaction.votes.added = added;
-								return cb(null, transaction);
-							});
+			if (transaction && transaction.asset && transaction.asset.votes) {
```
Comment (lsilvs) [inline lib/api/transactions.js]: I would move this entire block to a separated function as part of the async.waterfall
