### PR TITLE
Fix voters list on delegate page - Closes #502

### LINKED ISSUE #502: Voters list not showing on delegate page
### Expected behavior
The voters list should be shown when an address has voters

### Actual behavior
No voters are displayed

### Steps to reproduce
Giving you are using the [test database](https://downloads.lisk.io/lisk-explorer/dev/blockchain_explorer.db.gz):
Access /delegate/162664226572374905L 
You should see the voters list with 2 addresses

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
Voters list wasn't showing on delegate page

### How did I fix it?
I've fixed the getVoters calling it recursively until all voters are returned. That was required as core api limits the response to 100 items.
I also added an [issue](https://github.com/LiskHQ/lisk-explorer/issues/514) suggesting we improve the UI for this list adding pagination.

### How to test it?
Assuming you are using test data, access `delegate/3038510178697972178L` and you should see the list with 2 voters

### Review checklist
- The PR solves #502 
- All new code is covered with unit tests
- All new features are covered with e2e tests
- All new code follows best practices

### CODE REVIEW

File: lib/api/accounts.js [hunk 1]
```diff
@@ -190,26 +216,11 @@ module.exports = function (app) {
...
-					_.each(account.voters, (d) => {
-						d.knowledge = knowledge.inAccount(d);
-					});
-				} else {
-					account.voters = null;
-				}
-				return cb(null, account);
-			});
+			account.voters = [];
+			return this.getVotersCall(account, 100, 0, cb);
```
Comment (MichalTuleja) [inline lib/api/accounts.js]: We should avoid using literals as parameters. The literals above should be replaced with defined variables or constants. ex. `const limit = 100` and reference to the `limit` in the function params.
