### PR TITLE
Gaps between candles fix - Closes #425

### LINKED ISSUE #425: Poloniex candles are missing data
### Expected behaviour
https://explorer.lisk.io/api/exchanges/getCandles?e=poloniex&d=hour

should return data for each hour.

### Actual behaviour
https://explorer.lisk.io/api/exchanges/getCandles?e=poloniex&d=hour

returns data that ends with
```
{
"timestamp": 1518498000,
"date": "2018-02-13T05:00:00.000Z",
"high": "0.00315773",
"low": "0.00314747",
"open": "0.00314752",
"close": "0.00315773",
"liskVolume": "49.23464746",
"btcVolume": "0.15527021",
"firstTrade": 5295425,
"lastTrade": 5295445,
"nextEnd": 1518501545,
"numTrades": 21
},
{
"timestamp": 1518508800,
"date": "2018-02-13T08:00:00.000Z",
"high": "0.00315293",
"low": "0.00315293",
"open": "0.00315293",
"close": "0.00315293",
"liskVolume": "2.10831553",
"btcVolume": "0.00664737",
"firstTrade": 5295885,
"lastTrade": 5295885,
"nextEnd": 1518512379,
"numTrades": 1
},
{
"timestamp": 1518519600,
"date": "2018-02-13T11:00:00.000Z",
"high": "0.00319797",
"low": "0.00318839",
"open": "0.00319700",
"close": "0.00318839",
"liskVolume": "97.03797621",
"btcVolume": "0.31021105",
"firstTrade": 5296569,
"lastTrade": 5296573,
"nextEnd": 1518523154,
"numTrades": 5
},
{
"timestamp": 1518523200,
"date": "2018-02-13T12:00:00.000Z",
"high": "0.00315865",
"low": "0.00315865",
"open": "0.00315865",
"close": "0.00315865",
"liskVolume": "10.05668722",
"btcVolume": "0.03176556",
"firstTrade": 5296980,
"lastTrade": 5296980,
"nextEnd": 1518526781,
"numTrades": 1
},
{
"timestamp": 1518534000,
"date": "2018-02-13T15:00:00.000Z",
"high": "0.00316974",
"low": "0.00316973",
"open": "0.00316974",
"close": "0.00316973",
"liskVolume": "10.74323123",
"btcVolume": "0.03405319",
"firstTrade": 5297368,
"lastTrade": 5297370,
"nextEnd": 1518537549,
"numTrades": 3
}
]
}
```
the `date` param time values are `05`, `08`, 11`, `12`, `15`.

Also visible in the UI
screen shot 2018-02-13 at 17 23 36

### Steps to reproduce
Go to 
https://explorer.lisk.io/api/exchanges/getCandles?e=poloniex&d=hour

### PR DESCRIPTION
**Pull request by MichalTuleja**
### What was the problem?
The Market Watcher candles for Poloniex are built based on transaction data. Sometimes there are no transactions for a given period of time, in that (rare) case a gap between two candles can be visible. 

### How did I fix it?
I've created a separate function that looks for gaps in the data and fills it with candle objects accordingly.

### How to test it?
Go to the Market Watcher page, there should be no gaps visible.

UPDATE: That's the tricky part. Typically there are enough data for all candles to build. This error occurs rarely and only during the update procedure. It is never observed after a rebuild from scratch, but it may occur then as well.

### Review checklist
- The PR solves #425
- All new code is covered with unit tests
- All new features are covered with e2e tests
- All new code follows best practices

### CODE REVIEW

File: lib/candles/abstract.js [hunk 1]
```diff
@@ -107,6 +107,48 @@ function AbstractCandles(client) {
...
+
+		let index = 0;
+		do {
+			const curr = result[index];
+			const next = result[index + 1];
+
+			if ((curr.date.getTime() + delta) !== next.date.getTime()) {
+				// construct new candle and append it to the next array index
+				result.splice(index + 1, 0, {
+					btcVolume: curr.btcVolume,
```
Comment (MichalTuleja) [inline lib/candles/abstract.js]: Volume should be equal to 0

File: lib/candles/abstract.js [hunk 2]
```diff
@@ -107,6 +107,48 @@ function AbstractCandles(client) {
...
+					close: curr.close,
+					date: new Date(curr.date.getTime() + delta),
+					high: curr.close,
+					liskVolume: curr.liskVolume,
```
Comment (MichalTuleja) [inline lib/candles/abstract.js]: Also here: Volume should be equal to 0
