### PR TITLE
Market Watcher validation error - Closes #457 

### LINKED ISSUE #457: Market Watcher: Invalid response during update causes a process crash
Observer on a local machine, a response similar to that:
`{success: true, message: "", result: null}`

cause an unhandled exception:
```
TypeError: Cannot read property 'T' of undefined
    at BittrexCandles.__dirname.AbstractCandles.client.validData (/Users/michal/work/lisk-explorer-1.4/lib/candles/abstract.js:120:24)
```

### PR DESCRIPTION
**Pull request by MichalTuleja**
### What was the problem?
Wrong data incoming from external REST service could cause a process crash by raising an exception.

### How did I fix it?
I've added additional data type checks and fixed one bug I've noticed during a review.

### How to test it?
We need to observe the process on the testnet server.

### Review checklist
- The PR solves #457 
- All new code is covered with unit tests
- All new features are covered with e2e tests
- All new code follows best practices

### CODE REVIEW

File: lib/candles/abstract.js [hunk 1]
```diff
@@ -158,7 +158,7 @@ function AbstractCandles(client) {
 	};
 
 	this.validData = function (data) {
-		if (_.size(data) > 0) {
+		if (Array.isArray(data) && data.length > 0) {
 			return _.first(data)[self.validationKey];
 		}
 		return true;
```
Comment (4miners) [inline lib/candles/abstract.js]: Why it returns `true` for invalid data?

Comment (MichalTuleja) [reply lib/candles/abstract.js]: That's a good question. I've tried to "fix" it and it made things only worse. It can be written better way but it means more serious refactoring.
Also, notice that returning `true` here breaks the async loop, which is good assuming we don't want to retry on a request with an invalid data. The procedure assumes that everything that fails leads to retry, except the situation mentioned above.

Comment (4miners) [reply lib/candles/abstract.js]: Ok, so leave it as is. :)
